# Generated by Django 4.2.14 on 2024-07-15 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_farm_owner_alter_farm_horses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='farm',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='horses',
        ),
        migrations.AddField(
            model_name='horse',
            name='farm',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='farm.farm'),
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('duration', models.DurationField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.employee')),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.horse')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='horses',
            field=models.ManyToManyField(through='farm.TrainingSession', to='farm.horse'),
        ),
        migrations.AddField(
            model_name='horse',
            name='employees',
            field=models.ManyToManyField(through='farm.TrainingSession', to='farm.employee'),
        ),
    ]
